const fallbackSvg = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 24 24" fill="none" stroke="%23CBD5E1" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M8 12c0 2 2 4 4 4s4-2 4-4"/><path d="M10 8h.01"/><path d="M14 8h.01"/></svg>';

const imageMap = {
  "alfredo pasta": "Alfredo Pasta.jpg",
  "americano": "Americano.jpg",
  "arrabbiata pasta": "Arrabbiata Pasta.webp",
  "avocado toast": "Avocado Toast.jpg",
  "bbq chicken pizza": "BBQ Chicken Pizza.jpg",
  "black forest pastry": "Black Forest Pastry.jpg",
  "blueberry pastry": "Blueberry Pastry.jpg",
  "breakfast platter": "Breakfast Platter.jpg",
  "brownie with ice cream": "Brownie with Ice Cream.jpg",
  "burger fries and coke combo": "Burger Fries and Coke Combo.jpg",
  "butterscotch pastry": "Butterscotch Pastry.jpg",
  "caesar salad": "Caesar Salad.jpg",
  "cake and coffee combo": "Cake and Coffee Combo.jpg",
  "cappuccino": "Cappuccino.jpg",
  "caramel pudding": "Caramel Pudding.jpg",
  "carrot cake": "Carrot Cake.webp",
  "cheese burger": "Cheese Burger.jpg",
  "cheese corn sandwich": "Cheese Corn Sandwich.jpg",
  "cheese garlic bread": "Cheese Garlic Bread.webp",
  "cheesecake": "Cheesecake.webp",
  "chicken clear soup": "Chicken Clear Soup.jpg",
  "chicken nuggets": "Chicken Nuggets.jpg",
  "chicken salad": "Chicken Salad.jpg",
  "chicken sandwich": "Chicken Sandwich.jpg",
  "chicken wrap": "Chicken Wrap.jpg",
  "chocolate pastry": "Chocolate Pastry.jpg",
  "chocolate truffle cake": "Chocolate Truffle Cake.jpg",
  "classic veg burger": "Classic Veg Burger.jpg",
  "club sandwich": "Club Sandwich.jpg",
  "coffee and sandwich combo": "Coffee and Sandwich Combo.jpg",
  "cold coffee": "Cold Coffee.jpg",
  "crispy chicken burger": "Crispy Chicken Burger.jpg",
  "espresso": "Espresso.jpg",
  "falafel wrap": "Falafel Wrap.jpg",
  "farmhouse pizza": "Farmhouse Pizza.jpg",
  "french fries": "French Fries.jpg",
  "french toast": "French Toast.jpg",
  "fresh lime soda": "Fresh Lime Soda.jpg",
  "fruit cake": "Fruit Cake.jpg",
  "fruit punch": "Fruit Punch.jpg",
  "garden salad": "Garden Salad.jpg",
  "garlic bread": "Garlic Bread.webp",
  "granola bowl": "Granola Bowl.jpg",
  "greek salad": "Greek Salad.jpg",
  "green tea": "Green Tea.jpg",
  "hot and sour soup": "Hot and Sour Soup.jpg",
  "latte": "Latte.jpg",
  "loaded nachos": "Loaded Nachos.jpg",
  "mac and cheese": "Mac and Cheese.jpg",
  "margherita pizza": "Margherita Pizza.jpg",
  "masala tea": "Masala Tea.jpg",
  "mexican wrap": "Mexican Wrap.jpg",
  "mousse": "Mousse.jpg",
  "mozzarella sticks": "Mozzarella Sticks.jpg",
  "mushroom burger": "Mushroom Burger.jpg",
  "mushroom soup": "Mushroom Soup.jpg",
  "nachos": "Nachos.jpg",
  "omelette": "Omelette.jpg",
  "onion rings": "Onion Rings.jpg",
  "pancakes": "Pancakes.jpg",
  "paneer burger": "Paneer Burger.jpg",
  "paneer sandwich": "Paneer Sandwich.jpg",
  "paneer tikka wrap": "Paneer Tikka Wrap.jpg",
  "pasta and garlic bread combo": "Pasta and Garlic Bread Combo.jpg",
  "pepperoni pizza": "Pepperoni Pizza.jpg",
  "peri peri fries": "Peri Peri Fries.jpg",
  "pesto pasta": "Pesto Pasta.jpg",
  "pink sauce pasta": "Pink Sauce Pasta.jpg",
  "pizza and mocktail combo": "Pizza and Mocktail Combo.jpg",
  "potato wedges": "Potato Wedges.jpg",
  "quinoa salad": "Quinoa Salad.jpg",
  "red velvet cake": "Red Velvet Cake.jpg",
  "red velvet pastry": "Red Velvet Pastry.jpg",
  "scrambled eggs": "Scrambled Eggs.jpg",
  "spring rolls": "Spring Rolls.jpg",
  "sweet corn soup": "Sweet Corn Soup.jpg",
  "tiramisu": "Tiramisu.jpg",
  "tomato soup": "Tomato Soup.jpg",
  "tuna sandwich": "Tuna Sandwich.jpg",
  "veg grilled sandwich": "Veg Grilled Sandwich.jpg",
  "veg nuggets": "Veg Nuggets.jpg",
  "veggie delight pizza": "Veggie Delight Pizza.jpg",
  "veggie wrap": "Veggie Wrap.jpg",
  "virgin mojito": "Virgin Mojito.jpg",
  "waffle sundae": "Waffle Sundae.jpg",
  "waffles": "Waffles.jpg"
};

export const resolveImage = (productName) => {
  if (!productName) return fallbackSvg;
  const cleanName = productName.trim().toLowerCase();
  
  if (imageMap[cleanName]) {
    return `/mockup_images/${imageMap[cleanName]}`;
  }
  
  return fallbackSvg;
};
